import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import assert from "node:assert/strict";
import { buildAgentPromptContext } from "../src/agent/context.js";
import { createFixtureCodexRunner } from "../src/agent/codexRunner.js";
import { hydratePromptFile, prettyJson } from "../src/agent/prompts.js";
import { runLearnWorkflow } from "../src/agent/workflow.js";
import type { DriveHealthReport } from "../src/report/model.js";

test("prompt hydration uses redacted reports by default", async () => {
  const context = buildAgentPromptContext(privateReport());
  const prompt = await hydratePromptFile("explain-findings", {
    reportJson: prettyJson(context.report),
    remedyMetadataJson: prettyJson(context.remedyMetadata),
  });

  assert.equal(context.report.redaction.redacted, true);
  assert.doesNotMatch(prompt, /private-host/);
  assert.doesNotMatch(prompt, /\/home\/alice/);
  assert.doesNotMatch(prompt, /192\.168\.1\.50/);
  assert.match(prompt, /\[redacted-identifier\]/);
  assert.match(prompt, /\/home\/\[redacted-user\]/);
});

test("learn workflow writes review-only candidate artifacts from mocked Codex output", async () => {
  const root = mkdtempSync(join(tmpdir(), "drive-health-agent-"));
  try {
    const report = await readReport("test/fixtures/reports/sanitized-daedalus-report.json");
    const result = await runLearnWorkflow({
      report,
      runner: createFixtureCodexRunner("test/fixtures/codex"),
      candidatesDir: join(root, "candidate-remedies"),
      source: "local",
      openPr: true,
      topic: "Audit apt periodic cache cleanup policy.",
      evidenceUrls: ["https://manpages.debian.org/bookworm/apt/apt.systemd.daily.8.en.html"],
      now: new Date("2026-07-13T00:00:00.000Z"),
    });

    assert.equal(result.candidate.id, "audit-apt-periodic-cache-policy");
    assert.equal(result.reportRedacted, true);
    assert.match(result.paths.root, /candidate-remedies\/audit-apt-periodic-cache-policy$/);

    const candidateMarkdown = readFileSync(result.paths.remedyMarkdown, "utf8");
    assert.match(candidateMarkdown, /Review-only candidate generated by `drive-health learn`/);
    assert.match(candidateMarkdown, /Promotion requires a human-reviewed change/);
    assert.match(candidateMarkdown, /apt-get autoclean/);

    const reportFixture = readFileSync(result.paths.sanitizedReportFixture, "utf8");
    assert.match(reportFixture, /"redacted": true/);
    assert.doesNotMatch(reportFixture, /private-host|192\.168\.1\.50/);

    assert.ok(result.paths.prWorkflowMarkdown);
    const prWorkflow = readFileSync(result.paths.prWorkflowMarkdown, "utf8");
    assert.match(prWorkflow, /drive-health\/candidate-audit-apt-periodic-cache-policy/);
    assert.match(prWorkflow, /gh pr create --draft/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

async function readReport(path: string): Promise<DriveHealthReport> {
  return JSON.parse(await readFile(path, "utf8")) as DriveHealthReport;
}

function privateReport(): DriveHealthReport {
  return {
    schemaVersion: "drive-health.report.v1",
    generatedAt: "2026-07-13T00:00:00.000Z",
    target: "/home/alice",
    profile: "auto",
    redaction: {
      identifiersIncluded: true,
      redacted: false,
      rules: [],
    },
    host: {
      hostname: "private-host",
    },
    tools: [],
    blockDevices: [
      {
        name: "sda2",
        mountpoints: ["/home/alice/private"],
        uuid: "11111111-2222-3333-4444-555555555555",
      },
    ],
    filesystems: [],
    diskUsage: [],
    directoryUsage: [],
    trim: {
      timer: {
        unit: "fstrim.timer",
        status: "ok",
      },
      advertisedDiscard: "unknown",
      dryRun: {
        status: "ok",
        entries: [],
      },
    },
    journald: {
      storageMode: "auto",
      persistentDirectoryPresent: false,
      status: "ok",
      message: "private-host at 192.168.1.50",
    },
    swap: {
      devices: [],
      diskBackedSwapActive: false,
      zramDevices: [],
      status: "ok",
    },
    findings: [],
    sources: [],
  };
}
