import { chmodSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import assert from "node:assert/strict";
import { buildAgentPromptContext } from "../src/agent/context.js";
import { createCodexCliRunner, createFixtureCodexRunner } from "../src/agent/codexRunner.js";
import { hydratePromptFile, prettyJson } from "../src/agent/prompts.js";
import { runLearnWorkflow } from "../src/agent/workflow.js";
import type { DriveHealthReport } from "../src/report/model.js";

test("prompt hydration uses redacted reports by default", async () => {
  const context = buildAgentPromptContext(privateReport());
  const prompt = await hydratePromptFile("explain-findings", {
    reportJson: prettyJson(context.report),
    remedyMetadataJson: prettyJson(context.remedyMetadata),
  });

  assert.equal(context.report.redaction.redacted, true);
  assert.doesNotMatch(prompt, /private-host/);
  assert.doesNotMatch(prompt, /\/home\/alice/);
  assert.doesNotMatch(prompt, /192\.168\.1\.50/);
  assert.match(prompt, /\[redacted-identifier\]/);
  assert.match(prompt, /\/home\/\[redacted-user\]/);
});

test("learn workflow writes review-only candidate artifacts from mocked Codex output", async () => {
  const root = mkdtempSync(join(tmpdir(), "drive-health-agent-"));
  try {
    const report = await readReport("test/fixtures/reports/sanitized-daedalus-report.json");
    const result = await runLearnWorkflow({
      report,
      runner: createFixtureCodexRunner("test/fixtures/codex"),
      candidatesDir: join(root, "candidate-remedies"),
      source: "local",
      openPr: true,
      topic: "Audit apt periodic cache cleanup policy.",
      evidenceUrls: ["https://manpages.debian.org/bookworm/apt/apt.systemd.daily.8.en.html"],
      now: new Date("2026-07-13T00:00:00.000Z"),
    });

    assert.equal(result.candidate.id, "audit-apt-periodic-cache-policy");
    assert.equal(result.reportRedacted, true);
    assert.match(result.paths.root, /candidate-remedies\/audit-apt-periodic-cache-policy$/);

    const candidateMarkdown = readFileSync(result.paths.remedyMarkdown, "utf8");
    assert.match(candidateMarkdown, /Review-only candidate generated by `drive-health learn`/);
    assert.match(candidateMarkdown, /Promotion requires a human-reviewed change/);
    assert.match(candidateMarkdown, /apt-get autoclean/);

    const reportFixture = readFileSync(result.paths.sanitizedReportFixture, "utf8");
    assert.match(reportFixture, /"redacted": true/);
    assert.doesNotMatch(reportFixture, /private-host|192\.168\.1\.50/);

    assert.ok(result.paths.prWorkflowMarkdown);
    const prWorkflow = readFileSync(result.paths.prWorkflowMarkdown, "utf8");
    assert.match(prWorkflow, /drive-health\/candidate-audit-apt-periodic-cache-policy/);
    assert.match(prWorkflow, /gh pr create --draft/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("Codex CLI runner uses supported read-only noninteractive arguments", async () => {
  const root = mkdtempSync(join(tmpdir(), "drive-health-codex-runner-"));
  const commandPath = join(root, "fake-codex");
  const argsPath = join(root, "args.txt");
  const stdinPath = join(root, "stdin.txt");
  const previousArgsPath = process.env.DRIVE_HEALTH_CAPTURE_ARGS_PATH;
  const previousStdinPath = process.env.DRIVE_HEALTH_CAPTURE_STDIN_PATH;

  try {
    writeFileSync(commandPath, [
      "#!/bin/sh",
      "set -eu",
      "printf '%s\\n' \"$@\" > \"$DRIVE_HEALTH_CAPTURE_ARGS_PATH\"",
      "cat > \"$DRIVE_HEALTH_CAPTURE_STDIN_PATH\"",
      "output_path=''",
      "previous=''",
      "for argument in \"$@\"; do",
      "  if [ \"$previous\" = '--output-last-message' ]; then",
      "    output_path=\"$argument\"",
      "    break",
      "  fi",
      "  previous=\"$argument\"",
      "done",
      "if [ -z \"$output_path\" ]; then",
      "  echo 'missing --output-last-message path' >&2",
      "  exit 2",
      "fi",
      "printf 'fake codex response\\n' > \"$output_path\"",
      "",
    ].join("\n"));
    chmodSync(commandPath, 0o700);
    process.env.DRIVE_HEALTH_CAPTURE_ARGS_PATH = argsPath;
    process.env.DRIVE_HEALTH_CAPTURE_STDIN_PATH = stdinPath;

    const result = await createCodexCliRunner({
      command: commandPath,
      cwd: root,
      model: "gpt-5.6-sol",
      timeoutMs: 5000,
    }).run({
      promptName: "explain-findings",
      prompt: "Explain the sanitized report.",
    });

    const args = readFileSync(argsPath, "utf8").trim().split("\n");
    const configIndex = args.indexOf("-c");

    assert.equal(result.text, "fake codex response\n");
    assert.equal(args[0], "exec");
    assert.notEqual(configIndex, -1);
    assert.equal(args[configIndex + 1], "approval_policy=\"never\"");
    assert.equal(args[args.indexOf("--sandbox") + 1], "read-only");
    assert.equal(args[args.indexOf("--model") + 1], "gpt-5.6-sol");
    assert.equal(args.at(-1), "-");
    assert.equal(readFileSync(stdinPath, "utf8"), "Explain the sanitized report.");
    assert.equal(args.includes("--ask-for-approval"), false);
  } finally {
    restoreEnv("DRIVE_HEALTH_CAPTURE_ARGS_PATH", previousArgsPath);
    restoreEnv("DRIVE_HEALTH_CAPTURE_STDIN_PATH", previousStdinPath);
    rmSync(root, { recursive: true, force: true });
  }
});

async function readReport(path: string): Promise<DriveHealthReport> {
  return JSON.parse(await readFile(path, "utf8")) as DriveHealthReport;
}

function restoreEnv(name: string, value: string | undefined): void {
  if (value === undefined) {
    delete process.env[name];
    return;
  }

  process.env[name] = value;
}

function privateReport(): DriveHealthReport {
  return {
    schemaVersion: "drive-health.report.v1",
    generatedAt: "2026-07-13T00:00:00.000Z",
    target: "/home/alice",
    profile: "auto",
    redaction: {
      identifiersIncluded: true,
      redacted: false,
      rules: [],
    },
    host: {
      hostname: "private-host",
    },
    tools: [],
    blockDevices: [
      {
        name: "sda2",
        mountpoints: ["/home/alice/private"],
        uuid: "11111111-2222-3333-4444-555555555555",
      },
    ],
    filesystems: [],
    diskUsage: [],
    directoryUsage: [],
    trim: {
      timer: {
        unit: "fstrim.timer",
        status: "ok",
      },
      advertisedDiscard: "unknown",
      dryRun: {
        status: "ok",
        entries: [],
      },
    },
    journald: {
      storageMode: "auto",
      persistentDirectoryPresent: false,
      status: "ok",
      message: "private-host at 192.168.1.50",
    },
    swap: {
      devices: [],
      diskBackedSwapActive: false,
      zramDevices: [],
      status: "ok",
    },
    findings: [],
    sources: [],
  };
}
