import type { CandidateRemedyProposal } from "./model.js";

export function renderCandidateMarkdown(candidate: CandidateRemedyProposal, generatedAt: Date): string {
  return [
    `# ${candidate.title}`,
    "",
    "> Review-only candidate generated by `drive-health learn`.",
    "> The active apply engine does not load files from `candidate-remedies/`.",
    "",
    `Generated: ${generatedAt.toISOString()}`,
    `Candidate ID: \`${candidate.id}\``,
    `Risk: \`${candidate.risk.level}\``,
    "",
    "## Summary",
    "",
    candidate.summary,
    "",
    "## Promotion Boundary",
    "",
    "Promotion requires a human-reviewed change under `remedies/` and `src/remedies/`.",
    "Proposed commands below are review text only and are not executable by `drive-health apply`.",
    "",
    "## Evidence",
    "",
    ...candidate.evidence.map((entry) => `- ${formatEvidence(entry)}`),
    "",
    "## Compatibility",
    "",
    ...candidate.compatibility.map((entry) => `- ${entry}`),
    "",
    "## Risk",
    "",
    ...candidate.risk.notes.map((entry) => `- ${entry}`),
    "",
    "## Rollback",
    "",
    ...candidate.rollback.map((entry) => `- ${entry}`),
    "",
    "## Proposed Checks",
    "",
    ...commandLines(candidate.proposedChecks),
    "",
    "## Proposed Apply Commands",
    "",
    ...commandLines(candidate.proposedApplyCommands),
    "",
    "## Tests And Fixtures",
    "",
    "Tests:",
    ...candidate.testsAndFixtures.tests.map((entry) => `- ${entry}`),
    "",
    "Fixtures:",
    ...candidate.testsAndFixtures.fixtures.map((entry) => `- ${entry}`),
    "",
    "## Prompt Changes",
    "",
    ...listOrNone(candidate.promptChanges),
    "",
  ].join("\n");
}

export function renderEvidence(candidate: CandidateRemedyProposal): string {
  return [
    `# Evidence For ${candidate.id}`,
    "",
    ...candidate.evidence.flatMap((entry) => [
      `- Source: ${entry.source}`,
      entry.url ? `  URL: ${entry.url}` : undefined,
      entry.quote ? `  Quote: ${entry.quote}` : undefined,
      `  Relevance: ${entry.relevance}`,
    ].filter((line): line is string => Boolean(line))),
    "",
  ].join("\n");
}

export function renderRisk(candidate: CandidateRemedyProposal): string {
  return [
    `# Risk For ${candidate.id}`,
    "",
    `Level: \`${candidate.risk.level}\``,
    "",
    ...candidate.risk.notes.map((entry) => `- ${entry}`),
    "",
  ].join("\n");
}

export function renderTestsAndFixtures(candidate: CandidateRemedyProposal): string {
  return [
    `# Tests And Fixtures For ${candidate.id}`,
    "",
    "## Tests",
    "",
    ...candidate.testsAndFixtures.tests.map((entry) => `- ${entry}`),
    "",
    "## Fixtures",
    "",
    ...candidate.testsAndFixtures.fixtures.map((entry) => `- ${entry}`),
    "",
  ].join("\n");
}

export function renderListPage(title: string, entries: string[]): string {
  return [`# ${title}`, "", ...entries.map((entry) => `- ${entry}`), ""].join("\n");
}

export function renderCommands(title: string, commands: CandidateRemedyProposal["proposedChecks"]): string {
  return [
    `# ${title}`,
    "",
    ...commandLines(commands),
    commands.length === 0 ? "- none proposed" : undefined,
    "",
  ].filter((line): line is string => line !== undefined).join("\n");
}

export function renderPrWorkflow(candidate: CandidateRemedyProposal, prSummary: string, candidatePath: string): string {
  const branchName = `drive-health/candidate-${candidate.id}`;
  const commitMessage = `Add drive-health candidate remedy ${candidate.id}`;
  return [
    "# Candidate PR Workflow",
    "",
    "This is a prepared workflow packet. Review the candidate artifacts before running any git or GitHub commands.",
    "",
    "## Branch",
    "",
    `\`${branchName}\``,
    "",
    "## Commit Message",
    "",
    `\`${commitMessage}\``,
    "",
    "## Suggested Commands",
    "",
    "```bash",
    `git switch -c ${branchName}`,
    `git add ${candidatePath}`,
    `git commit -m "${commitMessage}"`,
    `gh pr create --draft --title "${commitMessage}" --body-file ${candidatePath}/pr-summary.md`,
    "```",
    "",
    "## PR Summary",
    "",
    prSummary.trim(),
    "",
  ].join("\n");
}

export function ensureTrailingNewline(value: string): string {
  return value.endsWith("\n") ? value : `${value}\n`;
}

function commandLines(commands: CandidateRemedyProposal["proposedChecks"]): string[] {
  return commands.map((command) => `- \`${command.command}\` - ${command.reason}`);
}

function formatEvidence(entry: { source: string; url?: string; relevance: string }): string {
  return entry.url ? `${entry.source} (${entry.url}) - ${entry.relevance}` : `${entry.source} - ${entry.relevance}`;
}

function listOrNone(entries: string[]): string[] {
  return entries.length > 0 ? entries.map((entry) => `- ${entry}`) : ["- none proposed"];
}
