import { join } from "node:path";
import type { HostProfile } from "../report/model.js";
import { DEFAULT_REPORT_RETENTION_COUNT } from "../state/reports.js";

export type RunnerScope = "user" | "system";
export type UnitStatus = "ok" | "missing" | "stale" | "invalid";

export const RUNNER_SERVICE_NAME = "drive-health-check.service";
export const RUNNER_TIMER_NAME = "drive-health-check.timer";
export const DEFAULT_USER_STATE_DIR = "%h/.local/state/drive-health";
export const DEFAULT_SYSTEM_STATE_DIR = "/var/lib/drive-health";
export const DEFAULT_ON_CALENDAR = "daily";
export const DEFAULT_RANDOMIZED_DELAY = "30m";
export const MANAGED_MARKER = "Managed by drive-health runner v1.";
export const EXAMPLE_BIN_PLACEHOLDER = "__DRIVE_HEALTH_BIN_ABSOLUTE_PATH__";
export const EXAMPLE_STATE_DIR_PLACEHOLDER = "__DRIVE_HEALTH_STATE_DIR__";

export interface RunnerUnitOptions {
  binPath: string;
  stateDir: string;
  profile: HostProfile;
  retentionCount: number;
  onCalendar: string;
  randomizedDelaySec: string;
}

export function defaultStateDir(scope: RunnerScope): string {
  return scope === "user" ? DEFAULT_USER_STATE_DIR : DEFAULT_SYSTEM_STATE_DIR;
}

export function unitDirectory(rootDir: string, scope: RunnerScope): string {
  return join(rootDir, scope === "user" ? "etc/systemd/user" : "etc/systemd/system");
}

export function renderRunnerServiceUnit(options: RunnerUnitOptions): string {
  return `# ${MANAGED_MARKER}
# Generated by: drive-health runner install
[Unit]
Description=Drive Health read-only check
Documentation=man:systemd.service(5)

[Service]
Type=oneshot
ExecStart=${options.binPath} check --profile ${options.profile} --write-report --quiet --state-dir ${options.stateDir} --retention-count ${options.retentionCount}
UMask=077
Nice=10
IOSchedulingClass=idle
NoNewPrivileges=yes
PrivateTmp=yes
`;
}

export function renderRunnerTimerUnit(options: RunnerUnitOptions): string {
  return `# ${MANAGED_MARKER}
# Generated by: drive-health runner install
[Unit]
Description=Run Drive Health read-only check
Documentation=man:systemd.timer(5)

[Timer]
OnCalendar=${options.onCalendar}
RandomizedDelaySec=${options.randomizedDelaySec}
Persistent=true
Unit=${RUNNER_SERVICE_NAME}

[Install]
WantedBy=timers.target
`;
}

export function renderExampleServiceUnit(): string {
  return renderRunnerServiceUnit({
    binPath: EXAMPLE_BIN_PLACEHOLDER,
    stateDir: EXAMPLE_STATE_DIR_PLACEHOLDER,
    profile: "pi-usb-flash",
    retentionCount: DEFAULT_REPORT_RETENTION_COUNT,
    onCalendar: DEFAULT_ON_CALENDAR,
    randomizedDelaySec: DEFAULT_RANDOMIZED_DELAY,
  });
}

export function renderExampleTimerUnit(): string {
  return renderRunnerTimerUnit({
    binPath: EXAMPLE_BIN_PLACEHOLDER,
    stateDir: EXAMPLE_STATE_DIR_PLACEHOLDER,
    profile: "pi-usb-flash",
    retentionCount: DEFAULT_REPORT_RETENTION_COUNT,
    onCalendar: DEFAULT_ON_CALENDAR,
    randomizedDelaySec: DEFAULT_RANDOMIZED_DELAY,
  });
}
